# This configuration was used Ebert to review the macedoj/jsf-morphia-mongodb-mdl repository
# on b462538a4e70d0607593473c9ea5f326df871b14.
# You can make this the default configuration for future reviews by moving this
# file to your repository as `.ebert.yml` and pushing it to GitHub, and tweak
# it as you wish - To know more on how to change this file to better review your
# repository you can go to https://docs.ebertapp.io/configuration and see the configuration
# details.
---
styleguide: plataformatec/linters
engines:
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: false
  remark-lint:
    enabled: true
exclude_paths: []

