#
# This codecov.yml is the configuration for github.com/JulianoR/simple-jsf-morphia-mdl
# 
codecov:
  branch: master  # override the default branch

  notify:
    require_ci_to_pass: yes   # yes: will delay sending notifications until all ci is finished
    countdown: 2           # number of seconds to wait before first ci build check
    delay: 5               # number of seconds to wait between ci build checks
 
coverage:
  precision: 2  # 2 = xx.xx%, 0 = xx%
  round: down|up|nearest # default down
  range: "50...100"

  status:
    # Learn more at https://codecov.io/docs#yaml_default_commit_status
    project: true
    patch: true
    changes: false

  ignore: null

comment:
  layout: "header, diff"
  behavior: default  # update if exists else create new
